//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfipAuth_bkp
    {
        public int IdAfipAuth { get; set; }
        public string Token { get; set; }
        public string Sign { get; set; }
        public string CuitRepresentado { get; set; }
        public Nullable<System.DateTime> GenerationTime { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public string Service { get; set; }
        public string UniqueID { get; set; }
    }
}
