//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class c1116aDetalle
    {
        public int Idc1116aDetalle { get; set; }
        public int Idc1116a { get; set; }
        public Nullable<int> NumeroCartaDePorte { get; set; }
        public Nullable<int> NumeroCertificadoAsociado { get; set; }
        public Nullable<decimal> KgBrutos { get; set; }
        public Nullable<System.DateTime> FechaRemesa { get; set; }
    }
}
