//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOperaciones
    {
        public int IdLogOperaciones { get; set; }
        public string Tabla { get; set; }
        public string Accion { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario { get; set; }
    }
}
