//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteCartasDePorte
    {
        public int IdLoteCartasDePorte { get; set; }
        public Nullable<int> Desde { get; set; }
        public Nullable<int> Hasta { get; set; }
        public string Cee { get; set; }
        public string EstablecimientoOrigen { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string UsuarioCreacion { get; set; }
        public int IdGrupoEmpresa { get; set; }
        public string Sucursal { get; set; }
        public string PuntoEmision { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<decimal> HabilitacionNum { get; set; }
    }
}
