//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int IdProveedor { get; set; }
        public string Sap_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipoDocumentoSAP { get; set; }
        public string NumeroDocumento { get; set; }
        public string Calle { get; set; }
        public string Piso { get; set; }
        public string Departamento { get; set; }
        public string Numero { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Domicilio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> EsProspecto { get; set; }
        public int IdSapOrganizacionDeVenta { get; set; }
    }
}
