//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesRecibidas
    {
        public int IdSolicitudRecibida { get; set; }
        public Nullable<int> IdTipoDeCarta { get; set; }
        public string NumeroCartaDePorte { get; set; }
        public string Cee { get; set; }
        public string Ctg { get; set; }
        public Nullable<System.DateTime> FechaDeEmision { get; set; }
        public Nullable<System.DateTime> FechaDeCarga { get; set; }
        public Nullable<System.DateTime> FechaDeVencimiento { get; set; }
        public string idProveedorTitularCartaDePorte { get; set; }
        public string IdClienteIntermediario { get; set; }
        public string IdClienteRemitenteComercial { get; set; }
        public string RemitenteComercialComoCanjeador { get; set; }
        public string IdClienteCorredor { get; set; }
        public string IdClienteEntregador { get; set; }
        public string IdClienteDestinatario { get; set; }
        public string IdClienteDestino { get; set; }
        public string IdProveedorTransportista { get; set; }
        public string IdChofer { get; set; }
        public Nullable<int> IdCosecha { get; set; }
        public Nullable<int> IdEspecie { get; set; }
        public Nullable<int> NumeroContrato { get; set; }
        public Nullable<int> SapContrato { get; set; }
        public Nullable<bool> SinContrato { get; set; }
        public Nullable<bool> CargaPesadaDestino { get; set; }
        public Nullable<decimal> KilogramosEstimados { get; set; }
        public string DeclaracionDeCalidad { get; set; }
        public Nullable<int> IdConformeCondicional { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoTara { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public string Observaciones { get; set; }
        public string LoteDeMaterial { get; set; }
        public string CodigoEstablecimientoProcedencia { get; set; }
        public Nullable<int> IdLocalidadEstablecimientoProcedencia { get; set; }
        public Nullable<int> IdEstablecimientoDestino { get; set; }
        public string PatenteCamion { get; set; }
        public string PatenteAcoplado { get; set; }
        public Nullable<decimal> KmRecorridos { get; set; }
        public Nullable<int> EstadoFlete { get; set; }
        public Nullable<decimal> CantHoras { get; set; }
        public Nullable<decimal> TarifaReferencia { get; set; }
        public Nullable<decimal> TarifaReal { get; set; }
        public Nullable<int> IdClientePagadorDelFlete { get; set; }
        public Nullable<int> EstadoEnSAP { get; set; }
        public Nullable<int> EstadoEnAFIP { get; set; }
        public Nullable<int> IdGrano { get; set; }
        public Nullable<decimal> CodigoAnulacionAfip { get; set; }
        public Nullable<System.DateTime> FechaAnulacionAfip { get; set; }
        public string CodigoRespuestaEnvioSAP { get; set; }
        public string MensajeRespuestaEnvioSAP { get; set; }
        public string CodigoRespuestaAnulacionSAP { get; set; }
        public string MensajeRespuestaAnulacionSAP { get; set; }
        public string CodigoEstablecimientoDestinoCambio { get; set; }
        public string CuitEstablecimientoDestinoCambio { get; set; }
        public Nullable<int> IdLocalidadEstablecimientoDestinoCambio { get; set; }
        public Nullable<System.DateTime> FechaDeDescarga { get; set; }
        public Nullable<System.DateTime> FechaDeArribo { get; set; }
        public Nullable<decimal> PesoNetoDescarga { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<int> IdChoferTransportista { get; set; }
        public int IdEmpresa { get; set; }
    }
}
