//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClienteDestinatarioCambio
    {
        public string IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public int IdEmpresa { get; set; }
    }
}
