//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRemitoParaguay
    {
        public int idsolicitud { get; set; }
        public string Descripcion { get; set; }
        public string Cee { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string NumeroRemision { get; set; }
        public Nullable<System.DateTime> FechaDeEmision { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string Direccion { get; set; }
        public string MotivoTraslado { get; set; }
        public string CteDeVta { get; set; }
        public string EPDireccion { get; set; }
        public string LocPartida { get; set; }
        public string ProvPartida { get; set; }
        public string EDDireccion { get; set; }
        public string LocLlegada { get; set; }
        public string ProvLlegada { get; set; }
        public Nullable<decimal> KmRecorridos { get; set; }
        public string TranspRazonSocial { get; set; }
        public string TransportistaCUIT { get; set; }
        public string MarcaVehiculo { get; set; }
        public string PatenteCamion { get; set; }
        public string PatenteAcoplado { get; set; }
        public string ChoferRazonSocial { get; set; }
        public string ChoferCUIT { get; set; }
        public string ChoferDomicilio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string KG { get; set; }
        public string DescripcionDetallada { get; set; }
        public Nullable<decimal> HabilitacionNum { get; set; }
    }
}
